targets:
  $default:
    builders:
      source_gen|combining_builder:
        options:
          build_extensions:
            {
              'lib/data/models/{{}}.dart': ['lib/data/generated/{{}}.g.dart'],
            }
